resources:
  - name: example_dbp_repo
    type: GitRepo
    configuration:
      gitProvider: pradnyashinde   # replace with your integration
      path: pradnyashinde/pipelines_docker_build_push    # replace with your repository name
      branches:
        include: master

  - name: build_info_dbp
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryIntegration  # replace with your Artifactory integration
      buildName: svc_build  # build name will be overwritten by pipeline name when used in Native steps
      buildNumber: 1  # build number will be overwritten by run number when used in Native steps

  - name: promoted_build_info_dbp
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryIntegration  # replace with your Artifactory integration
      buildName: svc_build  # build name will be overwritten by pipeline name when used in Native steps
      buildNumber: 1  # build number will be overwritten by run number when used in Native steps

pipelines:
  - name: example_docker_build_push_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.77.95.84:8082/docker-local/alpine37  # replace with the image name you want
          dockerImageTag: ${run_number}
          inputResources:
            - name: example_dbp_repo
          integrations:
            - name: ArtifactoryIntegration # replace with your Artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local  # replace if needed
          autoPublishBuildInfo: true
          integrations:
            - name: ArtifactoryIntegration # replace with your Artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: build_info_dbp

      #- name: publish_build_info
        #type: PublishBuildInfo
        #configuration:
          #inputSteps:
            #- name: docker_push
          #outputResources:
            #- name: build_info_dbp 

      - name: promote_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-prod  # replace with your target repo. Step will fail if this repo doesn't exist
          integrations:
            - name: ArtifactoryIntegration # replace with your Artifactory integration
          inputResources:
            - name: build_info_dbp
          outputResources:
            - name: promoted_build_info_dbp
